#----Pagina inicial
umespa_index:
    path:     /
    defaults: { _controller: umespaUserBundle:Default:index } # pasta 'src/umespa/userBundle/Resource/views/default'
    
#---------------------------------------------------------------   

#menu solicita carteirinha
umespa_criaConta:
    path:     /criaConta/{cad}
    defaults: { _controller: umespaUserBundle:AlunoController:criaConta } 
#Fazer Login
umespa_login:
    path:     /login
    defaults: { _controller: umespaUserBundle:AlunoController:login } 
#confirma email     
umespa_confirma:
    path:     /confirma/{token}
    defaults: { _controller: umespaUserBundle:AlunoController:confirma } 

#confirma email     
umespa_finalizar:
    path:     /finalizar
    defaults: { _controller: umespaUserBundle:AlunoController:finalizar }     

    
umespa_trataDadosTemp:
    path:     /trataDados
    defaults: { _controller: umespaUserBundle:AlunoController:trataDados } 
umespa_emitirCarteira:
    path:     /emitirCarteirinha
    defaults: { _controller: umespaUserBundle:AlunoController:emitirCarteirinha } 
umespa_checaIdade:
    path:     /checaIdade
    defaults: { _controller: umespaUserBundle:AlunoController:checaIdade } 


#send mail 
umespa_sendMail:
    path:     /sendMail
    defaults: { _controller: umespaUserBundle:AlunoController:sendMail } 

#rota para test de paginas
umespa_test:
    path:     /test
    defaults: { _controller: umespaUserBundle:AlunoController:test }     
    
index:
    path:     /index
    defaults: { _controller: umespaUserBundle:upload:index }

umespa_links:
    path:    /leiDaMeiaEntrada    
    defaults: { _controller: umespaUserBundle:Default:leiDaMeiaEntrada }