<?php

namespace umespa\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempRepository extends EntityRepository
{
}
